name: Dependency Update

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  update-python-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: pip install pip-tools

    - name: Update Python dependencies
      run: |
        pip-compile --upgrade requirements.in --output-file requirements.txt
        pip install -r requirements.txt

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: '🤖 Update Python Dependencies'
        body: |
          This PR updates Python dependencies to their latest versions.
          
          ## Changes
          - Updated Python packages in `backend/requirements.txt`
          
          ## Checklist
          - [ ] Tests pass
          - [ ] Code quality checks pass
          - [ ] Security scan passes
        branch: update-python-deps
        delete-branch: true

  update-node-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GitHub_Pages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: GitHub_Pages/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Update npm dependencies
      run: |
        npm update
        npm audit fix

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Node.js dependencies'
        title: '🤖 Update Node.js Dependencies'
        body: |
          This PR updates Node.js dependencies to their latest versions.
          
          ## Changes
          - Updated npm packages in `GitHub_Pages/package.json`
          - Updated `GitHub_Pages/package-lock.json`
          
          ## Checklist
          - [ ] Tests pass
          - [ ] Code quality checks pass
          - [ ] Security scan passes
        branch: update-node-deps
        delete-branch: true 