name: DRF Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: backend/requirements.txt

    - name: Install dependencies
      run: pip install -r backend/requirements.txt

    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=django-insecure-test-key-for-ci" >> $GITHUB_ENV
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "API_SERVER=False" >> $GITHUB_ENV
        echo "API_ENABLED=True" >> $GITHUB_ENV
        echo "WEBAPP_ENABLED=True" >> $GITHUB_ENV
        echo "WEB_ADMIN=True" >> $GITHUB_ENV
        echo "USER_REGISTRATION_ENABLED=True" >> $GITHUB_ENV
        echo "SELENIUM_ENABLED=False" >> $GITHUB_ENV

    - name: Create Migrations
      run: python backend/manage.py makemigrations mobileid

    - name: Run Migrations
      run: python backend/manage.py migrate

    - name: Run Django tests
      run: python backend/manage.py test