name: Full Application Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    
    services:
      sqlite:
        image: nouchka/sqlite3:latest
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run tests
      run: |
        cd backend
        python manage.py test
  
  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'GitHub_Pages/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd GitHub_Pages
        npm ci
    
    - name: Build
      run: |
        cd GitHub_Pages
        npm run build

  integration:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Install frontend dependencies
      run: |
        cd GitHub_Pages
        npm ci
    
    - name: Start Django server
      run: |
        cd backend
        python manage.py runserver &
        sleep 5
      
    - name: Build Vue app
      run: |
        cd GitHub_Pages
        npm run build
    
    - name: Check connectivity
      run: |
        curl -s -o /dev/null -w "%{http_code}" http://localhost:8000 | grep -q "200"