name: Deploy Vue to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: [ 'GitHub_Pages/**' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GitHub_Pages

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: GitHub_Pages/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Build production bundle
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: GitHub_Pages/dist

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
