name: Vue Frontend CI

on:
  push:
    branches: [ main ]
    paths: [ 'GitHub_Pages/**' ]
  pull_request:
    paths: [ 'GitHub_Pages/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: GitHub_Pages

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: GitHub_Pages/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --if-present

      - name: Build production bundle
        run: npm run build --if-present