name: Vue.js Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'GitHub_Pages/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'GitHub_Pages/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'GitHub_Pages/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd GitHub_Pages
        npm ci
    
    - name: Lint
      run: |
        cd GitHub_Pages
        npm run lint
    
    - name: Build
      run: |
        cd GitHub_Pages
        npm run build